@startuml

title Процесс добавления бизнес логики в Interactor

start
:Определение требований к бизнес-процессу;
:Поиск набора юзкейсов\nс помощью которого можно сформировать бизнес-процесс;
if (Есть реализации юзкейсов) then(да)
else (нет)
:Создание юзкейсов;
endif
:Добавление эндпоинта, указывающего на метод интерактора;
:Добавление метода в интерактор;
:Манипуляция юзкейсами, их порядком и входящими значениями;
stop
@enduml
