@startuml

title Процесс подключения юзкейса

start
:Определение зоны ответственности юзкейса;
if (Зона ответственности уже определена?) then (Да)
else (Нет)
:Добавить новый Scope в Enum;
:Создать инвокер для этого Scope;
endif

:Разместить юзкейс в доменной области;
:Прописать логику интеграции с модулем;
:Аннотировать класс необходимым Scope;
stop
@enduml
