@startuml

title Методология создания юзкейса

start
:Вычленение атомарной бизнес единицы;
:Определение зоны ответственности юзкейса;
:Определения входящих/выходящих параметров;
:Указание Scope;

if (Модуль является микросервисом?) then (да)
:Использование имплементации адаптера;
else (нет)
:Использование имплементации сервиса;
endif

:Реализация бизнес-единицы;

stop
@enduml
