services:
  local-database:
    image: 'postgres:16'
    networks:
      - app-network
    env_file:
      - env.yml
    container_name: local-database
    ports:
      - "5443:5432"
networks:
  app-network:
