# Modules

# Logging
logging:
  file:
    path: ./logs
  level:
    via:
      easyflow: DEBUG
    org:
      springframework: DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

datasource:
  host: &postgres_host ${POSTGRES_HOST}
  port: &postgres_port ${POSTGRES_PORT}
  name: &postgres_db ${POSTGRES_DB}
  user: &postgres_user ${POSTGRES_USER}
  password: &postgres_password ${POSTGRES_PASSWORD}
  driver: &postgresql postgresql

# App
server:
  servlet:
    context-path: /api
  port: 8090
spring:
  docker:
    compose:
      profiles:
        active: ${PROFILE}
      lifecycle-management: start_only
  profiles:
    active: ${PROFILE}
  application:
    name: easyflow
  datasource:
    driver-class-name: org.postgresql.Driver
    password: *postgres_password
    username: *postgres_user
    url: jdbc:postgresql://${datasource.host}:${datasource.port}/${datasource.name}