@startuml
|Работа фреймворка|
start

:Сканирование компонентов;

:Создание BeanDefinition;

|Работа созданной конфигурации|
:Начало регистрации BeanDefinition\nдля карты юзкейсов;

:Получение BeanDefinition с типом TypedUseCase;

repeat
    :определить скоуп юзкейса;
    :добавить в группу;
repeat while (Есть ли еще необработанные объекты?) is (да) not (нет)

repeat
    :создать BeanDefinition для группы;
    :добавить к нему Quialifier\nс указанием группы;
    :добавить к нему фабрику для создания бина;
repeat while (Есть ли еще необработанная группа?) is (да) not (нет)

:Создание бинов для групп;
|Работа фреймворка|
:Инъекция групп в классы - Invoker'ы;
stop
@enduml
