@startuml
object Client
object Controller
object Service
object Repository

Client -> Controller: 1:create(data)
Controller -> Service: 2:create(data)
Service -> Repository: 3:save(data)
Repository --> Service: 4:id
Service --> Controller: 5:result
Controller --> Client: 6:response
@enduml
